### PR TITLE
feat(endpoint): Add picker for endpoint

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by cmckni3** [comment]
Bump

**Comment by divyenduz** [comment]
Thanks for the PR. Some recent changes from my end caused some merge conflicts. Raised a PR to resolve them: https://github.com/cmckni3/vscode-graphql/pull/1

I tested the contents of this PR and they work as intended.

**Comment by cmckni3** [comment]
@divyenduz merged

**Comment by cmckni3** [comment]
Thanks for merging @divyenduz.

I had to fix some more conflicts before it could be merged. I think I fixed them correctly.

**Comment by divyenduz** [comment]
@cmckni3 : I will test it again before releasing (will notify you once a release is made). Thanks for notifying me.

**Comment by cmckni3** [comment]
Looks like this went out in 0.2.0 preview and seems to be functioning. Thanks!

image

**Comment by divyenduz** [comment]
@cmckni3 : Indeed, I wanted to notify you but you found it out already :) 

Thanks again for your work on making this possible 🙌

**Comment by cmckni3** [comment]
No problem. I enjoy using the extension and can help to improve when I have time. 😄

Let me know if I can help in other ways.

**Comment by divyenduz** [comment]
@cmckni3 : Feel free to pick up any issue from issues list that you feel strongly about and we can work together to make this extension better! Of course, when you have time :)

**Pull request merged**
