### PR TITLE
WIP: CI/CD setup using CircleCI

### PR DESCRIPTION
**Pull request by thakkaryash94**
for issue #45. This is a draft PR. I have set up the basic pipeline which will run test, package command and store artifact into `/tmp` folder. Next, we need to setup vsce workflow to publish the extension to the marketplace referring https://code.visualstudio.com/docs/extensions/publish-extension doc.

### CODE REVIEW

**Comment by divyenduz** [comment]
@thakkaryash94 This is awesome! Thanks for the PR. Does it also run test cases? Are there any test cases written? :)

**Comment by thakkaryash94** [comment]
Yes, it also runs `test` before package command. There is only 1 test case with below output.

```sh
xdg-settings: unknown desktop environment





  Extension Tests

    ✓ Something 1





  1 passing (4ms)



Tests exited with code: 0
```

**Comment by divyenduz** [comment]
@thakkaryash94 : Awesome! do you already want me to merge this or do you want to add more tests before that? :)

**Comment by thakkaryash94** [comment]
I think it will be better if we add this project and branch this ci-cd for testing in circleci and configure publishing extension

**Comment by divyenduz** [comment]
Thanks for the awesome work 🙌

**Comment by marktani** [comment]
woop woop 🎉

**Comment by thakkaryash94** [comment]
I think we also need to change the branch name in config.yml with the master so that it gets triggered when we push to master or we can set type to `approval` to only build, when we are ready for new version.

**Comment by divyenduz** [comment]
@thakkaryash94 : Adding `master` to the list sounds like a good idea, can you please create another PR? Thanks :)

**Pull request merged**
